package query

import (
	"fmt"
	"strings"

	"github.com/lokashrinav/codesearch/internal/storage"
)

// NarratedResult is the structured output for LLM consumption.
type NarratedResult struct {
	Summary string      `json:"summary"`
	Trace   []TraceItem `json:"trace"`
}

// TraceItem is one step in the narrated trace, formatted for the LLM.
type TraceItem struct {
	Step     int    `json:"step"`
	Symbol   string `json:"symbol"`
	Package  string `json:"package"`
	File     string `json:"file"`
	Line     int    `json:"line"`
	EdgeKind string `json:"edge_kind"`
	FlowType string `json:"flow_type"` // "definite" or "may"
	Detail   string `json:"detail"`
}

// Narrate converts a graph walk into a structured trace for LLM consumption.
func Narrate(query string, steps []TraceStep) *NarratedResult {
	result := &NarratedResult{}

	var traceItems []TraceItem
	for _, step := range steps {
		flowType := "definite"
		if step.FlowKind == storage.FlowMay {
			flowType = "may"
		}

		detail := formatEdgeDetail(step)

		traceItems = append(traceItems, TraceItem{
			Step:     step.StepNum + 1,
			Symbol:   step.Ident.Name,
			Package:  step.Ident.PkgPath,
			File:     step.Ident.File,
			Line:     step.Ident.Line,
			EdgeKind: step.EdgeKind,
			FlowType: flowType,
			Detail:   detail,
		})
	}
	result.Trace = traceItems

	// Build summary from the trace
	if len(traceItems) > 0 {
		var summaryParts []string
		summaryParts = append(summaryParts, fmt.Sprintf("Query: %q", query))
		summaryParts = append(summaryParts, fmt.Sprintf("Found %d connected symbols across %d hops.", len(traceItems), maxDepth(steps)))

		// Highlight key nodes
		for _, item := range traceItems {
			if item.EdgeKind == "seed" {
				summaryParts = append(summaryParts, fmt.Sprintf("Starting point: %s (%s)", item.Symbol, item.Package))
			}
		}

		result.Summary = strings.Join(summaryParts, " ")
	} else {
		result.Summary = fmt.Sprintf("No results found for query: %q", query)
	}

	return result
}

func formatEdgeDetail(step TraceStep) string {
	switch step.EdgeKind {
	case "seed":
		return fmt.Sprintf("Matched from query. %s in %s:%d", kindLabel(step.Ident.Kind), step.Ident.File, step.Ident.Line)
	case "calls":
		return fmt.Sprintf("Called by this function")
	case "called_by":
		return fmt.Sprintf("Calls this function")
	case "data_flow":
		return fmt.Sprintf("Data flows here (definite)")
	case "data_flow_may":
		return fmt.Sprintf("Data MAY flow here (via interface dispatch)")
	case "codegen":
		return fmt.Sprintf("Generated by codegen (stateify/protobuf)")
	case "shared_field":
		return fmt.Sprintf("Shares a struct field with previous node")
	default:
		return step.EdgeKind
	}
}

func kindLabel(k storage.IdentKind) string {
	switch k {
	case storage.IdentFunc:
		return "function"
	case storage.IdentType:
		return "type"
	case storage.IdentField:
		return "field"
	case storage.IdentMethod:
		return "method"
	case storage.IdentInterface:
		return "interface"
	case storage.IdentVar:
		return "variable"
	case storage.IdentConst:
		return "constant"
	default:
		return "identifier"
	}
}

func maxDepth(steps []TraceStep) int {
	max := 0
	for _, s := range steps {
		if s.StepNum > max {
			max = s.StepNum
		}
	}
	return max
}
